name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.0
        with:
          host: https://sonar.control4.com
          login: ${{ secrets.CLOUD_SERVICES_SONAR_TOKEN }}
